export const lightTheme = {
  name: 'light',
  colors: {
    primary: '#6366F1',
    primaryDark: '#4F46E5',
    secondary: '#10B981',
    background: '#FFFFFF',
    surface: '#F9FAFB',
    text: '#111827',
    textSecondary: '#6B7280',
    border: '#E5E7EB',
    error: '#EF4444',
    success: '#10B981',
    warning: '#F59E0B',
    card: '#FFFFFF',
    tabBar: '#FFFFFF',
    tabBarInactive: '#9CA3AF',
    inputBg: '#F3F4F6',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  typography: {
    h1: { fontSize: 32, fontWeight: '700' as const, lineHeight: 40 },
    h2: { fontSize: 24, fontWeight: '600' as const, lineHeight: 32 },
    h3: { fontSize: 20, fontWeight: '600' as const, lineHeight: 28 },
    body: { fontSize: 16, fontWeight: '400' as const, lineHeight: 24 },
    bodySmall: { fontSize: 14, fontWeight: '400' as const, lineHeight: 20 },
    caption: { fontSize: 12, fontWeight: '400' as const, lineHeight: 16 },
  },
};

export const darkTheme = {
  name: 'dark',
  colors: {
    primary: '#818CF8',
    primaryDark: '#6366F1',
    secondary: '#34D399',
    background: '#111827',
    surface: '#1F2937',
    text: '#F9FAFB',
    textSecondary: '#9CA3AF',
    border: '#374151',
    error: '#F87171',
    success: '#34D399',
    warning: '#FBBF24',
    card: '#1F2937',
    tabBar: '#1F2937',
    tabBarInactive: '#6B7280',
    inputBg: '#374151',
  },
  spacing: lightTheme.spacing,
  borderRadius: lightTheme.borderRadius,
  typography: lightTheme.typography,
};

export const gamingTheme = {
  name: 'gaming',
  colors: {
    primary: '#8B5CF6',
    primaryDark: '#7C3AED',
    secondary: '#06B6D4',
    background: '#0F0F1A',
    surface: '#1A1A2E',
    text: '#E0E7FF',
    textSecondary: '#A5B4FC',
    border: '#6366F1',
    error: '#F87171',
    success: '#34D399',
    warning: '#FBBF24',
    card: '#16213E',
    tabBar: '#0F0F1A',
    tabBarInactive: '#6B7280',
    inputBg: '#1A1A2E',
  },
  spacing: lightTheme.spacing,
  borderRadius: lightTheme.borderRadius,
  typography: {
    ...lightTheme.typography,
    h1: { ...lightTheme.typography.h1, fontSize: 36, textShadow: '0 0 10px #8B5CF6' },
    h2: { ...lightTheme.typography.h2, textShadow: '0 0 8px #8B5CF6' },
  },
};

export const professionalTheme = {
  name: 'professional',
  colors: {
    primary: '#2563EB',
    primaryDark: '#1D4ED8',
    secondary: '#059669',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    text: '#1E293B',
    textSecondary: '#64748B',
    border: '#E2E8F0',
    error: '#DC2626',
    success: '#059669',
    warning: '#D97706',
    card: '#FFFFFF',
    tabBar: '#FFFFFF',
    tabBarInactive: '#94A3B8',
    inputBg: '#F1F5F9',
  },
  spacing: lightTheme.spacing,
  borderRadius: {
    sm: 2,
    md: 4,
    lg: 6,
    xl: 8,
    full: 9999,
  },
  typography: {
    ...lightTheme.typography,
    h1: { ...lightTheme.typography.h1, fontWeight: '700' as const },
    h2: { ...lightTheme.typography.h2, fontWeight: '600' as const },
  },
};

export type Theme = typeof lightTheme;
export const themes = { light: lightTheme, dark: darkTheme, gaming: gamingTheme, professional: professionalTheme };